# Copyright (c) 2014, Erik Wienhold
# All rights reserved.
#
# Licensed under Creative Commons (CC BY-SA 4.0).

prefix :     <https://vsr.informatik.tu-chemnitz.de/projects/2014/cobalt/mashup#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?action ?offer
where {
  ?action :hasEffects [ :fillValueOf ?offer ] .
  ?offer :hasType/rdfs:subClassOf* ?request .
}
