# Copyright (c) 2014, Erik Wienhold
# All rights reserved.
#
# Licensed under Creative Commons (CC BY-SA 4.0).

prefix :     <https://vsr.informatik.tu-chemnitz.de/projects/2014/cobalt/mashup#>

select ?property ?type
where {
  ?property :hasType ?type .
  filter not exists { ?property :hasName [] }
}
